# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      strict: true
    )
  end

  desc "Run SwiftFormat"
  lane :format do
    swiftformat(
      directory: ".",
      swiftversion: "5.5"
    )
  end
  
  desc "Run SwiftLint, SwiftFormat, and Tests"
  lane :test_all do
    lint
    format
    scan(
      scheme: "Memorize",
      device: "iPhone 15",
      clean: true,
      code_coverage: true,
      output_directory: "./fastlane/test_output",
      output_types: "junit"
    )
  end
end
