name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6' # Match the Ruby version with your system

    - name: Install Fastlane
      run: brew install fastlane

    - name: Install dependencies
      run: bundle install

    - name: Run tests on iOS simulator
      run: fastlane test