name: iOS test case workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test Memorize scheme using any available iPhone simulator
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftLint
        run: |
          cd Memorize
          swiftlint
      - name: Run SwiftFormat
        run: |
          cd Memorize
          swiftformat .
      - name: Change directory to iOS project and run tests
        run: |
          cd Memorize
          fastlane test_all